name: Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize, closed]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  # build:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: 'npm'
  #         node-version: '16.17.0'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build
  #       run: npm run build
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: dist
  #         path: dist

  deploy:
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3 
      - uses: tzzs/server-shell@v3
        with:
          PRIVATE_KEY: ${{ secrets.KEY_AWS }}
          USERNAME: ${{secrets.USERNAME_SERVER}}
          IP: ${{secrets.IP_SERVER}}
          PORT: ${{secrets.PORT_SERVER}}

  deployPullRequest:
    runs-on: ubuntu-18.04          
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        run: |
          echo "$(git show -s --format=%s)"
      - name: Print head git show -s
        run: |
          echo "$(git show -s)"
      - name: Print head git pull request head sha
        run: |
          echo "$(github.event.pull_request.head)"
      - name: Print head git github.sha
        run: |
          echo "$(github.sha)"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: get the SHA MERGED
        run: |
          echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -2 | head -1 |sed 's/\"//g'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: get STATUS PULLREQUEST action 2
        run: |
          echo "$GITHUB_CONTEXT"| jq '.event.action'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: get the SHA CLOSED 1.4
        run: |
          echo "$GITHUB_CONTEXT"| jq '.event.pull_request.head.sha'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  pullRequestClosed:
    runs-on: ubuntu-18.04          
    if: |
      ${{ github.event_name == 'pull_request' }} &&
       ${{ github.event.action == 'closed' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: get STATUS PULLREQUEST action 2
        run: |
          echo "$GITHUB_CONTEXT"| jq '.event.action'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: get the SHA CLOSED 1.4
        run: |
          echo "$GITHUB_CONTEXT"| jq '.event.pull_request.head.sha'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  getPullRequestMerged:
    runs-on: ubuntu-18.04
    if: github.event_name == 'pull_request' && (github.event.pull_request.merged == true || github.event.pull_request.merged)
    steps:
      - uses: actions/checkout@v3
      - name: get the sha merged
        run: |
          echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -2 | head -1 |sed 's/\"//g'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      

